Repository loopbackio/loopback-next, pull requests merged in 2018-03, with the labels that each got.

#1046 feat: adding openapi-v3
  CODEOWNERS
  MONOREPO.md
  packages/openapi-v3-types/src/openapi-v3-spec-types.ts
  packages/openapi-v3/LICENSE
  packages/openapi-v3/README.md
  packages/openapi-v3/docs.json
  packages/openapi-v3/index.d.ts
  packages/openapi-v3/index.js
  packages/openapi-v3/index.ts
  packages/openapi-v3/package.json
  packages/openapi-v3/src/api-decorator.ts
  packages/openapi-v3/src/controller-spec.ts
  packages/openapi-v3/src/generate-schema.ts
  packages/openapi-v3/src/index.ts
  packages/openapi-v3/src/json-to-schema.ts
  packages/openapi-v3/src/keys.ts
  packages/openapi-v3/src/operation-decorator.ts
  packages/openapi-v3/src/parameter-decorator.ts
  packages/openapi-v3/src/request-body-decorator.ts
  packages/openapi-v3/src/spec-builder/openapi-v3-spec-builder.ts
  packages/openapi-v3/test/integration/controller-spec.test.ts
  packages/openapi-v3/test/integration/operation-spec.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/operation-decorators.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/param-decorators/param-header.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/param-decorators/param-path.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/param-decorators/param-query.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/param-decorators/param.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/request-body-decorators/primative-types.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/request-body-decorators/request-body.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/request-body-decorators/shortcut.test.ts
  packages/openapi-v3/test/unit/controller-spec/json-to-schema-object.test.ts
  packages/openapi-v3/tsconfig.build.json
Labels: needs-priority

#1066 fix(boot): fix spelling typos
  packages/boot/src/bootstrapper.ts
Labels: needs-priority

#1073 fix: update the generated commit message for lerna
  lerna.json
Labels: needs-priority

#1077 chore(openapi-v3): disable package-lock
  packages/openapi-v3/.npmrc
Labels: needs-priority

#1076 fix(boot): warn if attempts to call app.repository without RepositoryMixin
  packages/boot/src/booters/repository.booter.ts
  packages/boot/test/unit/booters/repository.booter.unit.ts
Labels: needs-priority

#1067 oas3/upgrade
  CODEOWNERS
  packages/authentication/package.json
  packages/authentication/test/acceptance/basic-auth.ts
  packages/boot/package.json
  packages/boot/test/fixtures/multiple.artifact.ts
  packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs
  packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.template
  packages/cli/generators/project/templates/package.json.ejs
  packages/cli/generators/project/templates/package.plain.json.ejs
  packages/cli/lib/dependencies.json
  packages/cli/test/app.js
  packages/cli/test/project.js
  packages/example-getting-started/docs/controller.md
  packages/example-getting-started/docs/model.md
  packages/example-getting-started/package.json
  packages/example-getting-started/src/controllers/todo.controller.ts
  packages/example-getting-started/src/models/todo.model.ts
  packages/example-log-extension/package.json
  packages/example-log-extension/test/acceptance/log.extension.acceptance.ts
  packages/openapi-spec-builder/package.json
  packages/openapi-spec-builder/src/openapi-spec-builder.ts
  packages/openapi-spec/README.md
  packages/openapi-v2/README.md
  packages/openapi-v2/src/openapi-spec-builder.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param.test.ts
  packages/openapi-v3/README.md
  packages/openapi-v3/src/index.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/operation-decorators.test.ts
  packages/openapi-v3/test/unit/controller-spec/controller-decorators/param-decorators/param.test.ts
  packages/rest/package.json
  packages/rest/src/http-handler.ts
  packages/rest/src/index.ts
  packages/rest/src/parser.ts
  packages/rest/src/rest-application.ts
  packages/rest/src/rest-component.ts
  packages/rest/src/rest-server.ts
  packages/rest/src/router/routing-table.ts
  packages/rest/test/acceptance/routing/routing.acceptance.ts
  packages/rest/test/acceptance/sequence/sequence.acceptance.ts
  packages/rest/test/integration/http-handler.integration.ts
  packages/rest/test/integration/rest-server.integration.ts
  packages/rest/test/unit/parser.test.ts
  packages/rest/test/unit/re-export.test.ts
  packages/rest/test/unit/rest-server/rest-server.open-api-spec.test.ts
  packages/rest/test/unit/router/routing-table.test.ts
  packages/testlab/package.json
  packages/testlab/src/validate-api-spec.ts
Labels: needs-priority

#1095 feat: drop v2 packages
  CODEOWNERS
  MONOREPO.md
  docs/apidocs.html
  packages/openapi-spec/.npmrc
  packages/openapi-spec/CHANGELOG.md
  packages/openapi-spec/LICENSE
  packages/openapi-spec/README.md
  packages/openapi-spec/docs.json
  packages/openapi-spec/index.d.ts
  packages/openapi-spec/index.js
  packages/openapi-spec/index.ts
  packages/openapi-spec/package.json
  packages/openapi-spec/src/index.ts
  packages/openapi-spec/src/openapi-spec-v2.ts
  packages/openapi-spec/tsconfig.build.json
  packages/openapi-v2/.npmrc
  packages/openapi-v2/CHANGELOG.md
  packages/openapi-v2/LICENSE
  packages/openapi-v2/README.md
  packages/openapi-v2/docs.json
  packages/openapi-v2/index.d.ts
  packages/openapi-v2/index.js
  packages/openapi-v2/index.ts
  packages/openapi-v2/package.json
  packages/openapi-v2/src/api-decorator.ts
  packages/openapi-v2/src/controller-spec.ts
  packages/openapi-v2/src/generate-schema.ts
  packages/openapi-v2/src/index.ts
  packages/openapi-v2/src/json-to-schema.ts
  packages/openapi-v2/src/keys.ts
  packages/openapi-v2/src/openapi-spec-builder.ts
  packages/openapi-v2/src/operation-decorator.ts
  packages/openapi-v2/src/parameter-decorator.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param-body.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param-form-data.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param-header.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param-path.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param-query.test.ts
  packages/openapi-v2/test/unit/controller-spec/controller-decorators/param-decorators/param.test.ts
  packages/openapi-v2/test/unit/controller-spec/json-to-schema-object.test.ts
  packages/openapi-v2/tsconfig.build.json
Labels: needs-priority

#1103 chore: work around apidocs rendering issue for openapi-v3
  packages/build/package.json
  packages/openapi-v3/src/parameter-decorator.ts
Labels: needs-priority

#1104 fix(rest): move @types/cors to dependency
  packages/rest/package.json
Labels: needs-priority

#1105 fix(repository-json-schema): change model to be a class
  packages/repository-json-schema/README.md
Labels: needs-priority

#1109 fix: template
  packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.template
  packages/cli/test/controller.js
Labels: needs-priority

#1111 refactor(cli): switch to .ejs extension
  packages/cli/generators/controller/index.js
  packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
  packages/cli/generators/controller/templates/src/controllers/controller-template.ts.ejs
  packages/cli/lib/project-generator.js
Labels: needs-priority

#1043 style: use lambda function to reset sandbox
  packages/boot/test/acceptance/controller.booter.acceptance.ts
  packages/boot/test/integration/controller.booter.integration.ts
  packages/boot/test/integration/repository.booter.integration.ts
  packages/boot/test/unit/booters/booter-utils.unit.ts
  packages/boot/test/unit/booters/controller.booter.unit.ts
  packages/boot/test/unit/booters/repository.booter.unit.ts
  packages/cli/test/clone-example.test.js
Labels: needs-priority

#1100 docs: move documentation into monorepo
  docs/Application-generator.md
  docs/Application.md
  docs/Best-practices-with-Loopback-4.md
  docs/Calling-other-APIs-and-Web-Services.md
  docs/Command-line-interface.md
  docs/Concepts.md
  docs/Context.md
  docs/Controller-generator.md
  docs/Controllers.md
  docs/Crafting-LoopBack-4.md
  docs/Creating-components.md
  docs/Creating-decorators.md
  docs/DEVELOPING.md
  docs/Decorators.md
  docs/Defining-and-validating-the-API.md
  docs/Defining-your-testing-strategy.md
  docs/Dependency-injection.md
  docs/Download-examples.md
  docs/Examples-and-tutorials.md
  docs/Extending-LoopBack-4.md
  docs/FAQ.md
  docs/Getting-started.md
  docs/Glossary.md
  docs/Implementing-features.md
  docs/Introduction-to-LoopBack-Next-development.md
  docs/Language-related-concepts.md
  docs/LoopBack-3.x.md
  docs/Mixin.md
  docs/Model.md
  docs/Preparing-the-API-for-consumption.md
  docs/Reference.md
  docs/Repositories.md
  docs/Reserved-binding-keys.md
  docs/Roadmap.md
  docs/Routes.md
  docs/Sequence.md
  docs/Server.md
  docs/Team.md
  docs/Testing-Your-Extensions.md
  docs/Testing-the-API.md
  docs/Testing-your-application.md
  docs/Using-components.md
  docs/Using-decorators.md
  docs/img/10000000.png
  docs/img/10000001.png
  docs/img/10000002.png
  docs/img/loopback-component.png
  docs/img/loopback-composition.png
  docs/img/loopback-ecosystem.png
  docs/img/loopback-extension.png
  docs/img/loopback-ioc.png
  docs/img/loopback-overview.png
  docs/img/loopback-stack.png
  docs/index.md
Labels: needs-priority

#1125 chore: switch to powered by loopback 4 logo
  docs/img/branding/Powered-by-LoopBack-Badge-(blue)-@2x.png
  packages/cli/generators/project/templates/README.md.ejs
Labels: needs-priority

#1122 chore: add `docs` as a package for loopback-next
  docs/package.json
  lerna.json
Labels: needs-priority

#1130 chore: update dependencies and refs to @types/node
  package.json
  packages/build/package.json
  packages/cli/generators/project/templates/package.json.ejs
  packages/cli/generators/project/templates/package.plain.json.ejs
  packages/cli/lib/dependencies.json
  packages/example-getting-started/package.json
  packages/example-hello-world/package.json
  packages/example-rpc-server/package.json
  packages/openapi-v3-types/package.json
  packages/repository-json-schema/package.json
  packages/rest/package.json
  packages/testlab/package.json
Labels: needs-priority

#1129 refactor: move all docs for loopback.io into site dir
  README.md
  docs/CONTRIBUTING.md
  docs/site/Application-generator.md
  docs/site/Application.md
  docs/site/Best-practices-with-Loopback-4.md
  docs/site/Calling-other-APIs-and-Web-Services.md
  docs/site/Command-line-interface.md
  docs/site/Concepts.md
  docs/site/Context.md
  docs/site/Controller-generator.md
  docs/site/Controllers.md
  docs/site/Crafting-LoopBack-4.md
  docs/site/Creating-components.md
  docs/site/Creating-decorators.md
  docs/site/DEVELOPING.md
  docs/site/Decorators.md
  docs/site/Defining-and-validating-the-API.md
  docs/site/Defining-your-testing-strategy.md
  docs/site/Dependency-injection.md
  docs/site/Download-examples.md
  docs/site/Examples-and-tutorials.md
  docs/site/Extending-LoopBack-4.md
  docs/site/FAQ.md
  docs/site/Getting-started.md
  docs/site/Glossary.md
  docs/site/Implementing-features.md
  docs/site/Introduction-to-LoopBack-Next-development.md
  docs/site/Language-related-concepts.md
  docs/site/LoopBack-3.x.md
  docs/site/MONOREPO.md
  docs/site/Mixin.md
  docs/site/Model.md
  docs/site/Preparing-the-API-for-consumption.md
  docs/site/Reference.md
  docs/site/Repositories.md
  docs/site/Reserved-binding-keys.md
  docs/site/Roadmap.md
  docs/site/Routes.md
  docs/site/Sequence.md
  docs/site/Server.md
  docs/site/Team.md
  docs/site/Testing-Your-Extensions.md
  docs/site/Testing-the-API.md
  docs/site/Testing-your-application.md
  docs/site/Using-components.md
  docs/site/Using-decorators.md
  docs/site/VSCODE.md
  docs/site/imgs/10000000.png
  docs/site/imgs/10000001.png
  docs/site/imgs/10000002.png
  docs/site/imgs/branding/Powered-by-LoopBack-Badge-(blue)-@2x.png
  docs/site/imgs/loopback-component.png
  docs/site/imgs/loopback-composition.png
  docs/site/imgs/loopback-ecosystem.png
  docs/site/imgs/loopback-extension.png
  docs/site/imgs/loopback-ioc.png
  docs/site/imgs/loopback-overview.png
  docs/site/imgs/loopback-stack.png
  docs/site/index.md
  packages/cli/generators/project/templates/README.md.ejs
Labels: needs-priority

#1123 refactor(core): use generics for type casting
  packages/core/src/application.ts
Labels: needs-priority

#1124 docs(core): update readme with latest code changes and links
  packages/core/README.md
Labels: needs-priority

#1128 fix(cli): update tsconfig.json to include index.ts
  packages/cli/generators/project/templates/tsconfig.json.ejs
Labels: needs-priority

#1135 chore: fix broken link to monorepo.md in contributing
  docs/CONTRIBUTING.md
Labels: needs-priority

#1131 fix(example-rpc-server): include index.ts in tsconfig
  packages/example-rpc-server/README.md
  packages/example-rpc-server/tsconfig.json
Labels: needs-priority

#1084 feat(rest): expose app.requestHandler function
  packages/authentication/test/acceptance/basic-auth.ts
  packages/boot/test/acceptance/controller.booter.acceptance.ts
  packages/cli/generators/app/templates/test/ping.controller.test.ts.ejs
  packages/cli/test/app-run.test.js
  packages/example-getting-started/test/acceptance/application.test.ts
  packages/example-log-extension/test/acceptance/log.extension.acceptance.ts
  packages/rest/src/rest-application.ts
  packages/rest/src/rest-server.ts
  packages/rest/test/acceptance/routing/routing.acceptance.ts
  packages/rest/test/acceptance/sequence/sequence.acceptance.ts
  packages/rest/test/integration/rest-server.integration.ts
Labels: REST, developer-experience, feature, needs-priority

#1113 fix(authentication): update broken code in README
  packages/authentication/README.md
Labels: needs-priority

#1141 Docs/finish migration from loopback.io
  docs/site/Application.md
  docs/site/Best-practices-with-Loopback-4.md
  docs/site/Booting-an-Application.md
  docs/site/Command-line-interface.md
  docs/site/Context.md
  docs/site/Decorators.md
  docs/site/Defining-the-API-using-code-first-approach.md
  docs/site/Defining-the-API-using-design-first-approach.md
  docs/site/Defining-your-testing-strategy.md
  docs/site/Examples-and-tutorials.md
  docs/site/Extending-LoopBack-4.md
  docs/site/Extension-generator.md
  docs/site/FAQ.md
  docs/site/Implementing-features.md
  docs/site/Preparing-the-API-for-consumption.md
  docs/site/Routes.md
  docs/site/Sequence.md
  docs/site/Server.md
  docs/site/Testing-your-application.md
  docs/site/sidebars/lb4_sidebar.yml
  docs/site/tables/lb4-artifact-commands.html
  docs/site/tables/lb4-project-commands.html
Labels: needs-priority

#1148 fix(testlab): fix throw() and rejectedWith() types
  packages/testlab/should-as-function.d.ts
Labels: needs-priority

#1136 chore: update loopback-3.x.md
  docs/site/LoopBack-3.x.md
Labels: needs-priority

#1155 docs(metadata): fix typo
  packages/metadata/README.md
Labels: needs-priority

#1147 docs: update installation, examples and production disclaimer
  README.md
Labels: needs-priority

#1156 docs: Fix typos and cleanup Model page
  docs/site/Model.md
Labels: needs-priority

#1167 chore: fix the travis build status badge url
  README.md
Labels: review

#1159 fix(example-getting-started): remove old model from sample data
  packages/example-getting-started/data/db.json
Labels: review

#1170 chore: add "docs update" to pull-request checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review

#1158 docs(rest): update readme
  packages/rest/README.md
Labels: needs-priority

#1168 refactor(example-getting-started): sync code and docs
  packages/example-getting-started/docs/controller.md
  packages/example-getting-started/docs/datasource.md
  packages/example-getting-started/docs/juggler.md
  packages/example-getting-started/docs/model.md
  packages/example-getting-started/docs/putting-it-together.md
  packages/example-getting-started/docs/repository.md
  packages/example-getting-started/docs/scaffolding.md
  packages/example-getting-started/src/application.ts
  packages/example-getting-started/src/controllers/todo.controller.ts
  packages/example-getting-started/src/index.ts
  packages/example-getting-started/src/sequence.ts
  packages/example-getting-started/test/acceptance/application.test.ts
Labels: review

#1175 chore: upgrade dependencies to latest versions
  package.json
  packages/build/package.json
  packages/cli/package.json
  packages/context/test/unit/resolution-session.ts
  packages/example-getting-started/package.json
  packages/example-hello-world/package.json
  packages/example-log-extension/package.json
  packages/example-log-extension/test/acceptance/log.extension.acceptance.ts
  packages/example-log-extension/test/unit/providers/log-action.provider.unit.ts
  packages/example-rpc-server/package.json
  packages/metadata/package.json
  packages/openapi-v3/package.json
  packages/repository-json-schema/package.json
  packages/repository/package.json
  packages/rest/package.json
  packages/testlab/package.json
Labels: review

#1161 fix: make small changes to Concepts.md
  docs/site/Concepts.md
Labels: review

#1162 docs: update route.md to use openapi-v3
  docs/site/Routes.md
Labels: review

#1121 fix(repository): fix broken code in readme
  packages/repository/README.md
Labels: needs-priority

#1180 fix(build): use variable names to reflect the accepted args
  packages/build/bin/run-clean.js
Labels: review

#1174 feat(context): add optional typing for Binding
  packages/context/src/binding.ts
  packages/context/src/context.ts
  packages/context/src/value-promise.ts
  packages/context/test/unit/value-promise.test.ts
Labels: review

#1178 docs: update contribution guidelines link and minor fixes
  README.md
  packages/authentication/README.md
  packages/boot/README.md
  packages/build/README.md
  packages/cli/README.md
  packages/context/README.md
  packages/core/README.md
  packages/example-getting-started/README.md
  packages/example-hello-world/README.md
  packages/example-log-extension/README.md
  packages/example-rpc-server/README.md
  packages/metadata/README.md
  packages/openapi-spec-builder/README.md
  packages/openapi-v3-types/README.md
  packages/openapi-v3/README.md
  packages/repository-json-schema/README.md
  packages/repository/README.md
  packages/testlab/README.md
Labels: needs-priority

#1157 docs: remove language-related-concepts.md
  docs/site/Creating-components.md
  docs/site/Language-related-concepts.md
  docs/site/sidebars/lb4_sidebar.yml
Labels: needs-priority

#1165 docs: update Repositories.md to use openapi-v3
  docs/site/Repositories.md
Labels: review

#1153 docs: fix code snippets in controllers.md
  docs/site/Controllers.md
Labels: needs-priority

#1146 docs: review and update of code snippets
  docs/site/Creating-components.md
  docs/site/Creating-servers.md
  docs/site/Extending-LoopBack-4.md
  docs/site/Testing-Your-Extensions.md
  docs/site/sidebars/lb4_sidebar.yml
Labels: review

#1176 docs: update using components page
  docs/site/Using-components.md
Labels: review

#1193 docs: update Application page
  docs/site/Application.md
Labels: review

#1195 docs(example-getting-started): fix typo for ds
  packages/example-getting-started/docs/datasource.md
Labels: review

#1192 docs: polish Dependency Injection article
  docs/site/Dependency-injection.md
Labels: review

#1198 fix(cli): remove automatic license generation
  packages/cli/generators/project/templates/LICENSE
  packages/cli/generators/project/templates/package.json.ejs
  packages/cli/generators/project/templates/package.plain.json.ejs
Labels: review

#1200 Remove unused script
  bin/build
Labels: review

#1145 docs: openapi v3 decorators
  docs/site/Decorators.md
Labels: needs-priority

#1203 docs(openapi-spec-builder): update README code snippet to v3
  packages/openapi-spec-builder/README.md
Labels: review

#1211 docs: upgrade controller-generator.md to v3
  docs/site/Controller-generator.md
Labels: review

#1196 docs: update code in Decorators.md
  docs/site/Decorators.md
Labels: review

#1212 chore: disable prefixed output for lerna run
  lerna.json
  package.json
Labels: review
