Repository loopbackio/loopback-next, pull requests merged in 2018-04, with the labels that each got.

#1214 docs: move todo tutorial to docs
  docs/site/todo-tutorial.md
  docs/site/todo-tutorial/add-controller.md
  docs/site/todo-tutorial/add-datasource.md
  docs/site/todo-tutorial/add-repository.md
  docs/site/todo-tutorial/add-todo-model.md
  docs/site/todo-tutorial/adding-legacy-juggler.md
  docs/site/todo-tutorial/controller.md
  docs/site/todo-tutorial/create-app-scaffolding.md
  docs/site/todo-tutorial/datasource.md
  docs/site/todo-tutorial/juggler.md
  docs/site/todo-tutorial/model.md
  docs/site/todo-tutorial/putting-it-all-together.md
  docs/site/todo-tutorial/putting-it-together.md
  docs/site/todo-tutorial/repository.md
  docs/site/todo-tutorial/scaffolding.md
  packages/cli/package.json
  packages/example-todo/README.md
Labels: review

#1216 fix: update sidebar links
  docs/site/sidebars/lb4_sidebar.yml
Labels: review

#1217 docs: fix miscellaneous errors/typos
  docs/site/Application.md
  docs/site/Context.md
  docs/site/Creating-components.md
Labels: review

#1219 docs: add includes folder + files
  docs/site/includes/CLI-std-options.md
Labels: review

#1224 fix: include openapi-v3-spec-types.ts in docs.json
  packages/openapi-v3-types/docs.json
Labels: review

#1222 docs: fix links and liquid formatting
  docs/site/Application-generator.md
  docs/site/Application.md
  docs/site/Best-practices-with-Loopback-4.md
  docs/site/Controller-generator.md
  docs/site/Creating-components.md
  docs/site/Defining-the-API-using-code-first-approach.md
  docs/site/Defining-the-API-using-design-first-approach.md
  docs/site/Defining-your-testing-strategy.md
  docs/site/Examples-and-tutorials.md
  docs/site/Implementing-features.md
  docs/site/Model.md
  docs/site/Preparing-the-API-for-consumption.md
  docs/site/Repositories.md
  docs/site/Reserved-binding-keys.md
  docs/site/Testing-the-API.md
  docs/site/Testing-your-application.md
  docs/site/index.md
  docs/site/sidebars/lb4_sidebar.yml
  docs/site/todo-tutorial-controller.md
  docs/site/todo-tutorial-datasource.md
  docs/site/todo-tutorial-juggler.md
  docs/site/todo-tutorial-model.md
  docs/site/todo-tutorial-putting-it-together.md
  docs/site/todo-tutorial-repository.md
  docs/site/todo-tutorial-scaffolding.md
  packages/cli/package.json
  packages/example-todo/README.md
Labels: review

#1226 refactor(authentication): extend strategy instead of implement
  packages/authentication/package.json
  packages/authentication/test/unit/authenticate-action.test.ts
  packages/authentication/test/unit/fixtures/mock-strategy.ts
  packages/authentication/test/unit/strategy-adapter.test.ts
Labels: review

#1229 chore: add Yaapa to maintainer list
  README.md
Labels: review

#1230 chore: update dependencies
  packages/boot/package.json
  packages/build/package.json
  packages/cli/package.json
  packages/context/package.json
  packages/example-hello-world/package.json
  packages/example-log-extension/package.json
  packages/example-rpc-server/package.json
  packages/example-todo/package.json
  packages/metadata/package.json
  packages/openapi-v3/package.json
  packages/repository-json-schema/package.json
  packages/rest/package.json
  packages/testlab/package.json
Labels: review

#1208 docs: add file naming convention
  docs/site/DEVELOPING.md
Labels: review

#1215 feat(repository): add getRepository function to mixin
  packages/example-todo/test/acceptance/application.test.ts
  packages/repository/src/repository-mixin.ts
  packages/repository/test/unit/repository-mixin/repository-mixin.test.ts
Labels: review

#1169 Introduce typed binding key
  docs/site/Context.md
  docs/site/Creating-components.md
  docs/site/Dependency-injection.md
  docs/site/Sequence.md
  examples/log-extension/README.md
  examples/log-extension/src/component.ts
  examples/log-extension/src/decorators/log.decorator.ts
  examples/log-extension/src/keys.ts
  examples/log-extension/src/mixins/log.mixin.ts
  examples/log-extension/src/providers/log-action.provider.ts
  packages/authentication/README.md
  packages/authentication/src/auth-component.ts
  packages/authentication/src/decorators/authenticate.ts
  packages/authentication/src/keys.ts
  packages/authentication/src/providers/authenticate.ts
  packages/authentication/test/unit/authenticate-action.test.ts
  packages/boot/src/keys.ts
  packages/cli/generators/app/templates/src/application.ts.ejs
  packages/cli/generators/app/templates/src/controllers/ping.controller.ts.ejs
  packages/context/src/BindingKey.ts
  packages/context/src/binding.ts
  packages/context/src/context.ts
  packages/context/src/index.ts
  packages/context/src/inject.ts
  packages/context/src/resolution-session.ts
  packages/context/test/acceptance/creating-and-resolving-bindings.ts
  packages/context/test/unit/BindingKey.test.ts
  packages/context/test/unit/binding.ts
  packages/context/test/unit/context.ts
  packages/core/src/keys.ts
  packages/rest/src/http-handler.ts
  packages/rest/src/keys.ts
  packages/rest/src/rest-component.ts
  packages/rest/src/router/routing-table.ts
  packages/rest/test/acceptance/routing/routing.acceptance.ts
  packages/rest/test/unit/rest-component.test.ts
  packages/rest/test/unit/rest-server/rest-server.test.ts
Labels: developer-experience, feature, needs-discussion, review

#1238 refactor(context): rename BindingKey.ts to binding-key.ts
  packages/context/src/binding-key.ts
  packages/context/src/binding.ts
  packages/context/src/context.ts
  packages/context/src/index.ts
  packages/context/src/inject.ts
  packages/context/src/resolution-session.ts
  packages/context/test/unit/binding-key.test.ts
Labels: review

#1242 refactor: add @types/node as a devDependency
  examples/hello-world/package.json
  examples/log-extension/package.json
  examples/rpc-server/package.json
  examples/todo/package.json
  package.json
  packages/authentication/package.json
  packages/boot/package.json
  packages/build/package.json
  packages/cli/package.json
  packages/context/package.json
  packages/core/package.json
  packages/metadata/package.json
  packages/openapi-spec-builder/package.json
  packages/openapi-v3-types/package.json
  packages/openapi-v3/package.json
  packages/repository-json-schema/package.json
  packages/repository/package.json
  packages/rest/package.json
  packages/testlab/package.json
Labels: review

#1213 fix(repository): clarify argument type for `@repository`
  docs/site/Controller-generator.md
  docs/site/Controllers.md
  docs/site/Decorators.md
  docs/site/Repositories.md
  docs/site/todo-tutorial-controller.md
  examples/todo/src/controllers/todo.controller.ts
  packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
  packages/cli/test/controller.js
  packages/repository/README.md
  packages/repository/src/decorators/repository.ts
  packages/repository/test/unit/decorator/repository-with-di.ts
Labels: review

#1241 test(openapi-v3-types): improve test coverage
  packages/openapi-v3-types/package.json
  packages/openapi-v3-types/test/unit/openapi-v3-spec-types.unit.ts
  packages/openapi-v3-types/test/unit/type-guards.unit.ts
  packages/testlab/package.json
  packages/testlab/src/validate-api-spec.ts
Labels: review

#951 feat(testlab): update sourceMappingURL when copying a JS file
  packages/boot/test/acceptance/controller.booter.acceptance.ts
  packages/boot/test/integration/controller.booter.integration.ts
  packages/boot/test/integration/repository.booter.integration.ts
  packages/boot/test/unit/booters/booter-utils.unit.ts
  packages/testlab/src/test-sandbox.ts
  packages/testlab/test/fixtures/test.ts
  packages/testlab/test/integration/test-sandbox.integration.ts
Labels: needs-priority, non-DP3

#1248 chore: force publish @loopback/docs and @loopback/cli
  bin/update-template-deps.js
  lerna.json
Labels: review

#1249 style(docs): fix syntax for include block
  docs/site/Context.md
Labels: review

#1246 chore(docs): disable package-lock
  docs/.npmrc
Labels: review

#1250 fix: change gitter logo
  README.md
Labels: review

#1240 Introduce strongly-typed metadata key
  packages/authentication/src/keys.ts
  packages/context/src/inject.ts
  packages/context/test/unit/binding-key.unit.ts
  packages/metadata/README.md
  packages/metadata/docs.json
  packages/metadata/src/decorator-factory.ts
  packages/metadata/src/index.ts
  packages/metadata/src/inspector.ts
  packages/metadata/src/types.ts
  packages/metadata/test/unit/inspector.unit.ts
  packages/metadata/test/unit/metadata-accessor.test.ts
  packages/openapi-v3/src/controller-spec.ts
  packages/openapi-v3/src/keys.ts
  packages/repository-json-schema/src/build-schema.ts
  packages/repository/src/decorators/metadata.ts
  packages/repository/src/decorators/model.decorator.ts
  packages/repository/test/unit/decorator/metadata.unit.ts
Labels: review

#1252 chore: add a sandbox location to enable testing w/ source code
  .gitignore
  lerna.json
  packages/cli/test/acceptance/app-run.acceptance.js
  sandbox/.gitignore
  sandbox/README.md
Labels: review

#1244 chore: update release name
  README.md
  packages/rest/README.md
Labels: review

#1266 chore(build): upgrade dependencies
  packages/build/package.json
Labels: review

#1265 feat: upgrade to openapi3-ts@0.11.0
  packages/openapi-v3-types/package.json
  packages/openapi-v3-types/src/openapi-v3-spec-types.ts
  packages/openapi-v3-types/test/unit/openapi-v3-spec-types.unit.ts
  packages/openapi-v3/src/controller-spec.ts
  packages/rest/src/http-handler.ts
  packages/rest/src/router/routing-table.ts
Labels: review

#1254 test: build loopback.io to validate docs package
  .travis.yml
  bin/verify-docs.sh
  package.json
Labels: review

#1273 fix: update the script to build/verify docs with loopback.io
  bin/build-docs-site.sh
  bin/verify-docs.sh
  package.json
Labels: review

#1271 refactor: clean usage of OAI's ExtensionValue
  packages/openapi-spec-builder/src/openapi-spec-builder.ts
  packages/openapi-v3-types/src/openapi-v3-spec-types.ts
  packages/openapi-v3-types/src/type-guards.ts
  packages/openapi-v3/src/json-to-schema.ts
Labels: review

#1263 feat(build): add an option to copy non ts files to outDir
  packages/build/README.md
  packages/build/bin/compile-package.js
  packages/build/config/tsconfig.build.json
  packages/build/package.json
  packages/testlab/test/integration/test-sandbox.integration.ts
Labels: review

#1281 chore: make the code compatible with node 10.0.0
  packages/authentication/test/acceptance/basic-auth.acceptance.ts
  packages/boot/src/booters/booter-utils.ts
  packages/build/package.json
  packages/repository/test/unit/type/type.unit.ts
Labels: review

#1279 feat(cli): improve cli help/version/commands options
  packages/cli/README.md
  packages/cli/bin/cli.js
  packages/cli/package.json
  packages/cli/test/acceptance/app-run.acceptance.js
  packages/cli/test/integration/cli/cli.integration.js
Labels: review

#1276 doc: list Testing guides under Best Practices
  docs/site/sidebars/lb4_sidebar.yml
Labels: review

#1284 ci: disable code coverage and linting on Windows
  appveyor.yml
Labels: developer-experience, review

#1283 chore: enable publishing of examples to npm
  examples/hello-world/package.json
  examples/log-extension/package.json
  examples/rpc-server/package.json
  examples/todo/package.json
Labels: feature, review

#1282 ci: enable node 10
  .travis.yml
  appveyor.yml
Labels: review

#1286 chore(repository-json-schema): replace JsonDefinition with JSONSchema6
  packages/openapi-v3/src/json-to-schema.ts
  packages/openapi-v3/test/unit/json-to-schema.unit.ts
  packages/repository-json-schema/package.json
  packages/repository-json-schema/src/build-schema.ts
  packages/repository-json-schema/src/index.ts
  packages/repository-json-schema/test/integration/build-schema.integration.ts
  packages/repository-json-schema/test/unit/build-schema.unit.ts
Labels: needs-priority

#1287 feat(cli): download examples via npm
  packages/cli/generators/example/clone-example.js
  packages/cli/generators/example/downloader.js
  packages/cli/generators/example/index.js
  packages/cli/package.json
  packages/cli/test/integration/generators/clone-example.integration.js
Labels: feature, review
