Repository loopbackio/loopback-next, pull requests merged in 2018-09, with the labels that each got.

#1667 feat: coerce object arguments from query strings
  docs/site/Parsing-requests.md
  packages/openapi-v3-types/package.json
  packages/openapi-v3/src/decorators/parameter.decorator.ts
  packages/openapi-v3/test/unit/decorators/param/param-query.decorator.unit.ts
  packages/rest/package.json
  packages/rest/src/coercion/coerce-parameter.ts
  packages/rest/src/coercion/utils.ts
  packages/rest/src/coercion/validator.ts
  packages/rest/src/parser.ts
  packages/rest/src/rest-http-error.ts
  packages/rest/src/rest.server.ts
  packages/rest/test/acceptance/coercion/coercion.acceptance.ts
  packages/rest/test/unit/coercion/paramObject.unit.ts
  packages/rest/test/unit/coercion/utils.ts
  packages/rest/test/unit/parser.unit.ts
Labels: REST, Validation, feature

#1689 fix(rest): use direct import to work around a TS bug
  packages/rest/package.json
  packages/rest/src/keys.ts
Labels: critical

#1734 feat(testlab): add createRestAppClient(), simplify usage in tests
  docs/site/Implementing-features.shelved.md
  docs/site/Testing-your-application.md
  examples/hello-world/test/acceptance/application.acceptance.ts
  examples/soap-calculator/test/acceptance/application.acceptance.ts
  examples/todo-list/test/acceptance/todo-list-todo.acceptance.ts
  examples/todo-list/test/acceptance/todo-list.acceptance.ts
  examples/todo-list/test/acceptance/todo.acceptance.ts
  examples/todo/test/acceptance/todo.acceptance.ts
  packages/boot/test/acceptance/controller.booter.acceptance.ts
  packages/cli/generators/app/templates/test/acceptance/ping.controller.acceptance.ts.ejs
  packages/rest/test/acceptance/bootstrapping/rest.acceptance.ts
  packages/rest/test/acceptance/coercion/coercion.acceptance.ts
  packages/rest/test/acceptance/validation/validation.acceptance.ts
  packages/testlab/README.md
  packages/testlab/src/client.ts
Labels: feature, refactor

#1733 feat(testlab): add a new helper `toJSON`
  packages/testlab/README.md
  packages/testlab/src/index.ts
  packages/testlab/src/to-json.ts
  packages/testlab/test/unit/to-json.test.ts
Labels: feature
