Repository loopbackio/loopback-next, pull requests merged in 2018-06, with the labels that each got.

#1388 chore: remove package specific .prettierrc
  packages/cli/.eslintrc.json
  packages/cli/.prettierrc
  packages/cli/package.json
  packages/cli/test/.eslintrc
  packages/dist-util/.prettierrc
Labels: review

#1363 feat(cli): auto-generate index.ts for exports
  docs/site/todo-tutorial-controller.md
  packages/cli/generators/app/templates/src/controllers/index.ts.ejs
  packages/cli/generators/controller/index.js
  packages/cli/lib/artifact-generator.js
  packages/cli/lib/update-index.js
  packages/cli/test/unit/update-index.unit.js
Labels: review

#1393 docs(testlab): describe Request/Response mocks
  packages/rest/test/unit/parser.unit.ts
  packages/testlab/README.md
Labels: needs-priority

#1392 test(repository): mark pending test with a skip
  packages/repository/test/acceptance/has-many.relation.acceptance.ts
Labels: review

#1445 docs: describe how to tests services
  docs/site/Calling-other-APIs-and-Web-Services.md
  docs/site/Testing-your-application.md
Labels: Docs

#1441 docs: add geo-coding service to Todo tutorial
  docs/site/sidebars/lb4_sidebar.yml
  docs/site/todo-tutorial-geocoding-service.md
  docs/site/todo-tutorial-putting-it-together.md
  examples/todo/README.md
  examples/todo/src/application.ts
  examples/todo/src/datasources/geocoder.datasource.ts
  examples/todo/src/datasources/index.ts
Labels: Docs, Examples
