Repository loopbackio/loopback-next, pull requests merged in 2018-05, with the labels that each got.

#1262 [RFC] feat(context): allow tags to have an optional value
  packages/context/src/binding.ts
  packages/context/src/context.ts
  packages/context/src/index.ts
  packages/context/test/acceptance/tagged-bindings.acceptance.ts
  packages/context/test/acceptance/tagged-bindings.feature.md
  packages/context/test/unit/binding.unit.ts
  packages/context/test/unit/context.unit.ts
  packages/core/test/unit/application.unit.ts
  packages/rest/test/unit/rest.server/rest.server.open-api-spec.unit.ts
Labels: review

#1119 feat: add integration for service-oriented backends
  docs/site/Calling-other-APIs-and-Web-Services.md
  packages/service-proxy/.npmrc
  packages/service-proxy/LICENSE
  packages/service-proxy/README.md
  packages/service-proxy/docs.json
  packages/service-proxy/index.d.ts
  packages/service-proxy/index.js
  packages/service-proxy/index.ts
  packages/service-proxy/package.json
  packages/service-proxy/src/decorators/service.decorator.ts
  packages/service-proxy/src/index.ts
  packages/service-proxy/src/legacy-juggler-bridge.ts
  packages/service-proxy/src/loopback-datasource-juggler.ts
  packages/service-proxy/test/integration/service-proxy.integration.ts
  packages/service-proxy/test/mock-service.connector.ts
  packages/service-proxy/test/unit/decorators/service-proxy.decorator.unit.ts
  packages/service-proxy/tsconfig.build.json
Labels: needs-priority

#1295 chore: parallelize travis
  .travis.yml
  bin/lint-commits.sh
  bin/travis.sh
  package.json
Labels: review

#1307 chore: rework binding key docs to point to apidocs
  docs/apidocs.html
  docs/site/Reserved-binding-keys.md
  packages/openapi-v3/src/keys.ts
  packages/repository-json-schema/src/keys.ts
Labels: review

#1338 refactor(rest): mount CORS as a regular middleware
  packages/rest/src/rest.server.ts
  packages/rest/test/integration/rest.server.integration.ts
Labels: REST

#1314 feat(cli): add prompt for plural model name
  docs/site/Controller-generator.md
  docs/site/Defining-the-API-using-code-first-approach.md
  docs/site/todo-tutorial-controller.md
  docs/site/todo-tutorial-putting-it-together.md
  examples/todo/src/controllers/todo.controller.ts
  examples/todo/test/acceptance/application.acceptance.ts
  packages/cli/generators/controller/index.js
  packages/cli/generators/controller/templates/src/controllers/controller-rest-template.ts.ejs
  packages/cli/lib/utils.js
  packages/cli/package.json
  packages/cli/test/integration/generators/controller.integration.js
  packages/cli/test/unit/utils.unit.js
Labels: needs-priority

#1364 Feature: a caching HTTP proxy for integration tests
  CODEOWNERS
  docs/apidocs.html
  docs/site/MONOREPO.md
  packages/http-caching-proxy/.npmrc
  packages/http-caching-proxy/LICENSE
  packages/http-caching-proxy/README.md
  packages/http-caching-proxy/docs.json
  packages/http-caching-proxy/index.d.ts
  packages/http-caching-proxy/index.js
  packages/http-caching-proxy/index.ts
  packages/http-caching-proxy/package.json
  packages/http-caching-proxy/src/http-caching-proxy.ts
  packages/http-caching-proxy/src/index.ts
  packages/http-caching-proxy/test/integration/http-caching-proxy.integration.ts
  packages/http-caching-proxy/test/unit/http-caching-proxy.test.ts
  packages/http-caching-proxy/tsconfig.build.json
Labels: review
