Repository loopbackio/loopback-next, pull requests merged in 2021-04, with the labels that each got.

#7342 monorepo: fix eslint vscode formatter; enforce consistent eol vscode
  .vscode/settings.json
Labels: Internal Tooling, developer-experience

#7326 fix: cli openapi generator op name inference
  packages/cli/generators/openapi/spec-helper.js
  packages/cli/test/unit/openapi/spec-helper.unit.js
Labels: CLI, developer-experience

#7407 docs: correct ServiceBooter Options in README
  packages/boot/README.md
Labels: Docs
